Feature/component/progress
AchievedOwner/TDesignBlazor pull request #105
Opened 2022-09-26 08:45 UTC by wuxinheng

## 合并请求（ Pull Request ）
> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。

### 合并请求的必要条件
- 必要的单元测试已经完成
- 完成必要的注释，包括参数、方法、属性、类等
- 代码风格必须符合 C# 的代码规范

### 本次合并的类型是什么？
- [ ] 缺陷修复（对缺陷的修复，包括紧急修复和一般修复） 
- [ ] 功能开发（新功能、特性的开发，之前功能的完善等）
- [ ] 代码风格（包括命名规范、格式、优化代码的写法等）
- [ ] 文档更新（仅对当前版本的文档进行增加、完善和更新）
- [ ] 重构（没有新功能，仅对代码的重构、调整）
- [ ] 测试（单元测试、集成测试、性能测试、压力测试等）
- [ ] 其他，请在下面进行描述：
   > 其他描述写在这里
   
### 关联的 ISSUE 编号
ISSUE 编号：

### 关于本次更新的主要内容
重构进度条代码，优化逻辑，完善环形进度条百分比

### 其他相关信息

### 期望参与合并请求评审的成员
@AchievedOwner 

> **再次感谢贡献者的辛苦付出，良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。**

2022-09-26 14:42 UTC, AchievedOwner requested changes
* `ProgresInner` `ProgressInfo` `ProgressBar` 这个三个类似乎没有必要存在，返回会对用户造成困扰
* 组件代码编写过于复杂，可能还是不太熟悉 `ComponentBuilder` 的用法造成的

2022-09-26 14:42 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Progress/Progress.cs
> +            theme.CreateComponent<ProgressInfo>(sequence + 2, Percentage.ToSuffix("%"), attributes: new { Percentage, Status, Theme, Label });
这个 `ToSuffix` 有啥用？可以使用 `$"{Percentage}%"` 语法代替

2022-09-27 03:31 UTC, wuxinheng commented on src/TDesignBlazor/Components/Progress/Progress.cs
> +            theme.CreateComponent<ProgressInfo>(sequence + 2, Percentage.ToSuffix("%"), attributes: new { Percentage, Status, Theme, Label });
`ProgresInner` `ProgressBar` 进行了删除 `ProgressInfo` 进行了改名,优化了一点逻辑

2022-10-08 09:47 UTC, AchievedOwner approved these changes

2022-10-08 09:50 UTC, AchievedOwner approved these changes

2022-10-08 10:00 UTC, merged