Feature/component/image
AchievedOwner/TDesignBlazor pull request #109
Opened 2022-09-28 06:49 UTC by wuxinheng

## 合并请求（ Pull Request ）
> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。

### 合并请求的必要条件
- 必要的单元测试已经完成
- 完成必要的注释，包括参数、方法、属性、类等
- 代码风格必须符合 C# 的代码规范

### 本次合并的类型是什么？
- [ ] 缺陷修复（对缺陷的修复，包括紧急修复和一般修复） 
- [x] 功能开发（新功能、特性的开发，之前功能的完善等）
- [ ] 代码风格（包括命名规范、格式、优化代码的写法等）
- [ ] 文档更新（仅对当前版本的文档进行增加、完善和更新）
- [ ] 重构（没有新功能，仅对代码的重构、调整）
- [ ] 测试（单元测试、集成测试、性能测试、压力测试等）
- [ ] DevOps （CI/CD、git action 等）
- [ ] 其他，请在下面进行描述：
   > 其他描述写在这里
   
### 关联的 ISSUE 编号
ISSUE 编号：#106

### 关于本次更新的主要内容
完成基础image功能

### 期望参与合并请求评审的成员
@AchievedOwner 

### 其他相关信息
如果有，请写明

> **再次感谢贡献者的辛苦付出，良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。**

2022-09-29 14:45 UTC, AchievedOwner requested changes

2022-09-29 14:45 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Image.cs
> +                onmouseenter = JS.Value.InvokeAsync<object>("alert", "1")
这是几个意思？

2022-09-30 01:59 UTC, wuxinheng commented
已经修改以上建议

2022-09-30 03:34 UTC, AchievedOwner requested changes
在示例代码中的源代码中，请遵循以下规范：
- 示例代码是展示给用户如何使用组件的，不要把运行代码直接放到示例代码中，会给用户产生不必要的一些使用问题
- 不要包含任何与组件无关的其他布局代码

2022-09-30 03:34 UTC, AchievedOwner commented on doc/TDesignBlazor.Docs.Shared/Pages/Components/ImagePage.razor
> +        <Space Vertical style="width: 100%">
`Space` 用错了吧？

2022-09-30 03:34 UTC, AchievedOwner commented on doc/TDesignBlazor.Docs.Shared/Pages/Components/ImagePage.razor
> +        <Space Vertical style=""width: 100%"">
示例代码不要包含无用的布局代码

2022-09-30 03:34 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Image.cs
> +                //x.CreateElement(sequence + 1, "div", "预览", new { style = "background: rgba(0, 0, 0, 0.4); color: rgb(255, 255, 255); height: 100%; display: flex; align-items: center; justify-conten
没实现的代码就删除

2022-09-30 03:34 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Image.cs
> +        [Parameter] public Position Position { get; set; } = TDesignBlazor.Position.Center; //[CssClass("t-image--position-")]
注释掉的代码没必要就删除

2022-09-30 03:34 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Image.cs
> +                x.CreateElement(sequence + 1, "span", span =>
这个可使用 `Tag` 以简化默认的 css

2022-09-30 03:37 UTC, AchievedOwner requested changes
![image](https://user-images.githubusercontent.com/52902266/193184800-f5ddc364-0789-4f00-a90c-a228516c0d3f.png)
这个标题是属于上面图片还是下面的？标题与最靠近的展示距离最近，与其他元素具备一定间隔

2022-09-30 05:20 UTC, AchievedOwner approved these changes

2022-09-30 05:21 UTC, AchievedOwner approved these changes

2022-09-30 07:24 UTC, AchievedOwner approved these changes

2022-09-30 07:25 UTC, AchievedOwner requested changes

2022-09-30 07:25 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Image.cs
> +                             .Append("t-image--position-" + Position.GetCssClass()),
避免字符串的 `+` 操作，要么使用 `string.Format` 要么使用模板字符串

2022-09-30 08:22 UTC, AchievedOwner approved these changes

2022-09-30 08:35 UTC, merged