fix: 菜单使用NavLink作为a标签跳转
AchievedOwner/TDesignBlazor pull request #110
Opened 2022-09-29 05:58 UTC by ElderJames

## 合并请求（ Pull Request ）
> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。

### 合并请求的必要条件
- 必要的单元测试已经完成
- 完成必要的注释，包括参数、方法、属性、类等
- 代码风格必须符合 C# 的代码规范

### 本次合并的类型是什么？
- [x] 缺陷修复（对缺陷的修复，包括紧急修复和一般修复） 
- [ ] 功能开发（新功能、特性的开发，之前功能的完善等）
- [ ] 代码风格（包括命名规范、格式、优化代码的写法等）
- [ ] 文档更新（仅对当前版本的文档进行增加、完善和更新）
- [ ] 重构（没有新功能，仅对代码的重构、调整）
- [ ] 测试（单元测试、集成测试、性能测试、压力测试等）
- [ ] DevOps （CI/CD、git action 等）
- [ ] 其他，请在下面进行描述：
   > 其他描述写在这里
   
### 关联的 ISSUE 编号
ISSUE 编号：

### 关于本次更新的主要内容
请详细描述，描述得越详细，评审通过的几率就越高

### 期望参与合并请求评审的成员
使用 `@名字`来提及你期望参与本次评审人成员 

### 其他相关信息
如果有，请写明

> **再次感谢贡献者的辛苦付出，良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。**

2022-09-29 14:52 UTC, AchievedOwner requested changes

2022-09-29 14:52 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> +        builder.CreateElement(sequence, "span", Link is not { Length: > 0 } ? ChildContent : buider =>
在官方的代码中，不需要进行下一级的 a 元素渲染
![image](https://user-images.githubusercontent.com/52902266/193065126-4d765a14-354f-4c1b-9208-74e6e9a268a6.png)

2022-09-29 17:34 UTC, ElderJames commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> +        builder.CreateElement(sequence, "span", Link is not { Length: > 0 } ? ChildContent : buider =>
那是因为没有链接，链接是加了a标签实现的

2022-09-30 00:42 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> +        builder.CreateElement(sequence, "span", Link is not { Length: > 0 } ? ChildContent : buider =>
> 那是因为没有链接，链接是加了a标签实现的

所以这个组件的这段代码
```cs
protected override void BuildAttributes(IDictionary<string, object> attributes)
{
    if (CanNavigationChanged && !string.IsNullOrWhiteSpace(Link))
    {
        attributes["href"] = Link;
        attributes["onclick"] = HtmlHelper.CreateCallback(this, NavigateTo);
    }
}
```
是否还应该存在或修改？
![image](https://user-images.githubusercontent.com/52902266/193165926-1298c862-52e2-411a-8044-b6a2cd21bbba.png)

2022-09-30 03:24 UTC, ElderJames commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> +        builder.CreateElement(sequence, "span", Link is not { Length: > 0 } ? ChildContent : buider =>
不应该存在了，不应该放在li上

2022-09-30 03:51 UTC, AchievedOwner requested changes

2022-09-30 03:51 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> -    protected override void BuildAttributes(IDictionary<string, object> attributes)
移除后将导致只点击菜单的文字才会有跳转效果

2022-09-30 03:58 UTC, ElderJames commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> -    protected override void BuildAttributes(IDictionary<string, object> attributes)
这是样式的问题，应该吧a标签宽度100%

2022-09-30 05:28 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> -    protected override void BuildAttributes(IDictionary<string, object> attributes)
![image](https://user-images.githubusercontent.com/52902266/193196834-7a9268b2-d4fb-4b8e-a3da-de35d273c112.png)
目测没有对 a 元素设置 block

2022-09-30 05:31 UTC, ElderJames commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> -    protected override void BuildAttributes(IDictionary<string, object> attributes)
挺尴尬的，给他们pr吧

2022-09-30 05:32 UTC, ElderJames commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> -    protected override void BuildAttributes(IDictionary<string, object> attributes)
可能他们是想放Link组件

2022-09-30 07:22 UTC, AchievedOwner commented on src/TDesignBlazor/Components/Menu/MenuItem.cs
> -    protected override void BuildAttributes(IDictionary<string, object> attributes)
我也不晓得这算不算一个bug，说不定故意的 😅 :

2022-10-10 10:49 UTC, closed without merging

2022-10-10 10:50 UTC, AchievedOwner commented
这个变更暂时不需要