Feature/components/anchor
AchievedOwner/TDesignBlazor pull request #184
Opened 2022-12-05 09:35 UTC by wuxinheng

## 合并请求（ Pull Request ）
>新增 Anchor 

### 关于本次更新的主要内容
> Anchor基本使用，包括一定js 动态效果

### 本次合并的类型是什么？
- [ ] 缺陷修复（对缺陷的修复，包括紧急修复和一般修复） 
- [×] 功能开发（新功能、特性的开发，之前功能的完善等）
- [ ] 代码风格（包括命名规范、格式、优化代码的写法等）
- [ ] 文档更新（仅对当前版本的文档进行增加、完善和更新）
- [ ] 重构（没有新功能，仅对代码的重构、调整）
- [ ] 测试（单元测试、集成测试、性能测试、压力测试等）
- [ ] DevOps （CI/CD、git action 等）
- [ ] 其他，请在下面进行描述：
   > 其他描述写在这里
   
### 关联的 ISSUE 编号
ISSUE 编号：

### 其他相关信息

> 非常感谢您对本项目的贡献，所有的合并请求最终将由作者通过才可以合并成功。并且要求贡献者需要谦虚地对待每一次评审的内容，并且尊重每一位贡献者的回复。良好的规范才能让项目健康的运转，保持利他精神才是我们一直信奉的价值观。

2022-12-05 09:40 UTC, elvismile reviewed
.vscode 目录是不是应该加入到忽略目录列表？ @AchievedOwner @wuxinheng

2022-12-05 09:49 UTC, elvismile requested changes
`tdesign-blazor.js`里新增的js方法考虑用初始化的形式包一层js，因为有其他组件也在用这个js文件，可能会引起添加多余的事件给window对象。可以参照master分支上的写法

2022-12-05 10:28 UTC, elvismile commented on doc/TDesign.Docs.ServerSide/Pages/_Layout.cshtml
> +    <script src="_content/TDesign/tdesign-blazor.js"></script>
建议该js文件在组件内通过Import的形式访问，可参照Affix或Popup组件的方式

2022-12-06 02:48 UTC, AchievedOwner requested changes

2022-12-06 02:48 UTC, AchievedOwner commented on src/TDesign/Components/Anchor/TAnchorItem.cs
> +    public class TAnchorItem : BlazorComponentBase, IHasChildContent, IHasActive
这个组件应该必须放在 `TAnchor` 下吧？请设置特性 `ChildComponentAttribute` 强关联

2022-12-06 03:21 UTC, wuxinheng commented on src/TDesign/JsRuntimeExtensions.cs
> +        public static async Task ScrollToHash(this IJSRuntime js, string hash)
已经删除

2022-12-06 03:32 UTC, wuxinheng commented on src/TDesign/Components/Anchor/TAnchorItem.cs
> +    public class TAnchorItem : BlazorComponentBase, IHasChildContent, IHasActive
ok

2022-12-06 10:13 UTC, AchievedOwner approved these changes

2022-12-07 06:03 UTC, AchievedOwner approved these changes

2022-12-07 06:23 UTC, elvismile approved these changes

2022-12-07 06:30 UTC, AchievedOwner approved these changes

2022-12-07 06:36 UTC, merged